# Generated by Django 3.0.8 on 2020-07-22 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Events', '0001_initial'),
        ('Athletes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Club', '0002_auto_20200722_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='participants',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Events.Events'),
        ),
        migrations.AddField(
            model_name='participants',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Club.Club'),
        ),
        migrations.AddField(
            model_name='events',
            name='club_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Club.Club'),
        ),
        migrations.AddField(
            model_name='events',
            name='sport_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Athletes.Sports'),
        ),
    ]
