# Generated by Django 3.0.8 on 2020-07-21 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Club', '0002_auto_20200721_1522'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Athletes', '0001_initial'),
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='participants',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Events.Events'),
        ),
        migrations.AddField(
            model_name='participants',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Club.MembersClub'),
        ),
        migrations.AddField(
            model_name='events',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Club.Club'),
        ),
        migrations.AddField(
            model_name='events',
            name='participants_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Events.Participants'),
        ),
        migrations.AddField(
            model_name='events',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Athletes.Sports'),
        ),
    ]
