# Generated by Django 3.0.8 on 2020-07-27 14:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_auto_20200724_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='average_hr',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='average_speed',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='workout',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='workout',
            name='distance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='workout',
            name='heart_rate',
            field=models.IntegerField(blank=True, choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=1),
        ),
        migrations.AlterField(
            model_name='workout',
            name='latitude',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='workout',
            name='longitude',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AlterField(
            model_name='workout',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='workout',
            name='workout_effectiveness',
            field=models.IntegerField(),
        ),
    ]
