# Generated by Django 3.0.8 on 2020-07-22 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0002_auto_20200722_0901'),
        ('Events', '0002_auto_20200722_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participants',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Club.MembersClub'),
        ),
    ]
