# Generated by Django 3.0.8 on 2020-07-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Athletes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sports',
            name='description',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
