# Generated by Django 3.0.8 on 2020-07-21 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0003_auto_20200721_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='description',
        ),
    ]
