# Generated by Django 3.0.8 on 2020-07-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0004_remove_club_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
