# Generated by Django 3.0.8 on 2020-07-15 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_name', models.CharField(max_length=255, unique=True, verbose_name='Sport Name')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='primary_sport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Primary', to='user_auth.Sports'),
        ),
        migrations.AddField(
            model_name='user',
            name='secondary_sport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Seconndary', to='user_auth.Sports'),
        ),
    ]
