# Generated by Django 3.0.8 on 2020-07-16 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_auto_20200715_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='primary_sport',
            field=models.ForeignKey(blank=True, help_text='Choose a primary sport.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Primary', to='user_auth.Sports'),
        ),
        migrations.AlterField(
            model_name='user',
            name='secondary_sport',
            field=models.ForeignKey(blank=True, help_text='Choose a secondary sport.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Seconndary', to='user_auth.Sports'),
        ),
    ]
