# Generated by Django 3.0.8 on 2020-07-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_auto_20200716_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='primary_sport',
        ),
        migrations.RemoveField(
            model_name='user',
            name='secondary_sport',
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(0, 'Admin'), (1, 'Coach'), (2, 'Athlete')], default=0, verbose_name='Role'),
        ),
        migrations.DeleteModel(
            name='Sports',
        ),
    ]
