# Generated by Django 3.0.8 on 2020-07-16 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Athlets', '0001_initial'),
        ('user_auth', '0004_auto_20200716_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='primary_sport',
            field=models.ForeignKey(blank=True, help_text='Choose a primary sport.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Primary', to='Athlets.Sports'),
        ),
        migrations.AddField(
            model_name='user',
            name='secondary_sport',
            field=models.ForeignKey(blank=True, help_text='Choose a secondary sport.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Secondary', to='Athlets.Sports'),
        ),
    ]
